{
  "name": "clauseiq-backend",
  "description": "ClauseIQ Backend - FastAPI service for document analysis",
  "version": "1.0.0",
  "build": { "commands": ["pip install -r requirements.txt"] },
  "deploy":
    {
      "startCommand": "uvicorn main:app --host 0.0.0.0 --port $PORT",
      "healthcheckPath": "/",
      "numInstances": 1,
    },
  "envVars":
    [
      {
        "key": "OPENAI_API_KEY",
        "description": "OpenAI API key for AI-powered summaries",
      },
      { "key": "MONGODB_URI", "description": "MongoDB connection string" },
      {
        "key": "CORS_ORIGINS",
        "description": "Allowed CORS origins",
        "defaultValue": "https://your-vercel-domain.vercel.app,http://localhost:3000",
      },
    ],
}
